train_cols = ['fBodyGyro-maxInds-X', 'fBodyAcc-mean()-Y', 'fBodyAccJerk-mad()-Y', 'tBodyAccJerk-mad()-Y',
              'fBodyAccMag-mad()', 'tBodyGyroJerk-mean()-Z', 'tBodyGyro-std()-X', 'tBodyAccJerk-std()-Y',
              'tBodyAcc-std()-Z', 'tBodyAcc-mad()-Y', 'fBodyAccJerk-energy()-Y', 'fBodyGyro-bandsEnergy()-17,24',
              'fBodyGyro-kurtosis()-Z', 'tBodyGyro-min()-X', 'fBodyAccJerk-bandsEnergy()-17,32',
              'tBodyGyroJerk-arCoeff()-Z,2', 'tBodyAcc-arCoeff()-X,3', 'tBodyAccJerk-max()-X',
              'tBodyGyroJerkMag-std()', 'tBodyGyro-arCoeff()-X,3', 'tBodyAccJerkMag-iqr()',
              'tBodyAcc-correlation()-X,Y', 'fBodyAcc-bandsEnergy()-17,32', 'tBodyAccJerk-arCoeff()-X,2',
              'fBodyAcc-bandsEnergy()-25,32', 'tBodyGyroJerkMag-energy()', 'tGravityAcc-arCoeff()-Y,1',
              'tBodyAccJerk-mad()-Z', 'fBodyAccJerk-entropy()-Z', 'tBodyGyroJerk-mad()-X', 'tBodyGyro-energy()-Z',
              'fBodyBodyAccJerkMag-max()', 'fBodyAcc-max()-X', 'tGravityAccMag-iqr()', 'fBodyGyro-bandsEnergy()-49,64',
              'fBodyBodyGyroJerkMag-kurtosis()', 'fBodyGyro-bandsEnergy()-17,32', 'tBodyAccJerk-max()-Y',
              'fBodyBodyAccJerkMag-energy()', 'fBodyGyro-bandsEnergy()-1,24', 'tBodyGyro-max()-X',
              'fBodyAcc-mean()-X', 'fBodyAccMag-sma()', 'tBodyGyroMag-mad()', 'tBodyAcc-min()-X',
              'tBodyGyroJerk-arCoeff()-Z,4', 'tBodyAccMag-arCoeff()3', 'tBodyGyro-mean()-Z',
              'fBodyAccJerk-skewness()-X', 'fBodyAccJerk-min()-X', 'fBodyGyro-iqr()-Z', 'tGravityAcc-mean()-Y',
              'tBodyGyroJerk-entropy()-Y', 'tBodyGyroJerk-mad()-Y', 'tBodyAcc-entropy()-Z', 'tBodyGyroJerk-max()-Z',
              'fBodyAcc-kurtosis()-Y', 'tBodyAcc-correlation()-X,Z', 'tBodyGyroJerk-mean()-X',
              'fBodyBodyGyroJerkMag-iqr()', 'tBodyAcc-entropy()-X', 'tGravityAcc-max()-Z', 'tBodyAcc-min()-Z',
              'tGravityAcc-correlation()-X,Z', 'fBodyAccJerk-sma()', 'tBodyAccMag-energy()', 'fBodyAcc-entropy()-Z',
              'tBodyAcc-std()-Y', 'tBodyAcc-energy()-Y', 'fBodyGyro-mad()-Y', 'tBodyAccJerk-correlation()-X,Y',
              'tBodyGyroJerk-entropy()-Z', 'fBodyAcc-entropy()-Y', 'tGravityAcc-arCoeff()-X,4', 'fBodyAcc-energy()-X',
              'fBodyAcc-min()-Y', 'tBodyGyro-correlation()-X,Z', 'tBodyAccJerkMag-min()', 'tBodyGyro-arCoeff()-X,2',
              'fBodyAccJerk-skewness()-Z', 'tBodyAccMag-entropy()', 'fBodyGyro-bandsEnergy()-33,40',
              'tBodyGyroJerkMag-arCoeff()4', 'fBodyAccJerk-mean()-X', 'fBodyAccJerk-kurtosis()-Y',
              'tBodyGyroJerk-sma()', 'fBodyBodyGyroMag-entropy()', 'fBodyAccJerk-max()-Z',
              'tBodyAccJerk-arCoeff()-Z,1', 'tBodyGyro-iqr()-X', 'fBodyGyro-std()-X', 'fBodyAcc-bandsEnergy()-57,64',
              'tGravityAccMag-mean()', 'tBodyGyro-min()-Z', 'tGravityAcc-arCoeff()-X,2', 'tBodyGyroMag-energy()',
              'fBodyGyro-min()-Y', 'tBodyAcc-max()-Y', 'tBodyAcc-iqr()-Y', 'fBodyAcc-max()-Z',
              'tBodyGyroJerk-arCoeff()-Y,3', 'tGravityAccMag-std()', 'fBodyAccMag-mean()', 'fBodyAccMag-maxInds',
              'tBodyGyroJerk-mean()-Y', 'tBodyGyroJerk-min()-Z', 'tBodyGyro-arCoeff()-Y,1',
              'fBodyBodyGyroJerkMag-mean()', 'tBodyAccJerk-correlation()-X,Z', 'fBodyGyro-skewness()-Z',
              'fBodyAccJerk-kurtosis()-Z', 'tGravityAcc-sma()', 'fBodyAccJerk-max()-Y', 'tBodyGyroMag-iqr()',
              'tBodyGyroJerk-arCoeff()-X,4', 'fBodyGyro-min()-Z', 'fBodyAccJerk-meanFreq()-Y',
              'tGravityAccMag-arCoeff()1', 'tBodyGyroMag-arCoeff()1', 'fBodyAccJerk-bandsEnergy()-1,8',
              'fBodyBodyAccJerkMag-kurtosis()', 'tBodyGyroJerk-iqr()-Z', 'tBodyAccJerk-mad()-X',
              'fBodyAccJerk-mean()-Z', 'fBodyGyro-maxInds-Y', 'tBodyAcc-arCoeff()-X,4', 'tGravityAcc-iqr()-X',
              'fBodyAccJerk-min()-Y', 'fBodyAccJerk-meanFreq()-Z', 'tGravityAcc-iqr()-Z',
              'fBodyAccJerk-kurtosis()-X', 'tBodyAcc-correlation()-Y,Z', 'tBodyAcc-arCoeff()-X,1',
              'tGravityAcc-arCoeff()-Z,3', 'tBodyGyroJerkMag-sma()', 'fBodyBodyAccJerkMag-iqr()',
              'fBodyAccJerk-iqr()-Y', 'fBodyGyro-bandsEnergy()-57,64', 'fBodyAcc-skewness()-X',
              'fBodyAcc-min()-Z', 'tBodyGyroJerkMag-arCoeff()1', 'fBodyBodyAccJerkMag-std()',
              'tBodyAcc-arCoeff()-Z,3', 'tGravityAcc-min()-Y', 'tBodyAcc-arCoeff()-Y,3', 'tBodyAccJerk-std()-Z',
              'tBodyGyro-mad()-Z', 'tBodyAccJerk-arCoeff()-Y,2', 'tBodyGyro-arCoeff()-Z,3',
              'tGravityAcc-correlation()-Y,Z', 'tBodyGyro-correlation()-Y,Z', 'fBodyAccJerk-energy()-X',
              'angle(tBodyAccJerkMean),gravityMean)', 'tBodyAccJerkMag-std()', 'fBodyGyro-bandsEnergy()-25,48',
              'tBodyGyroJerk-arCoeff()-Y,1', 'fBodyAcc-std()-Z', 'angle(X,gravityMean)', 'tBodyAcc-mean()-X',
              'tGravityAcc-arCoeff()-Z,4', 'fBodyBodyAccJerkMag-meanFreq()', 'fBodyAccJerk-maxInds-Y',
              'tBodyAcc-iqr()-X', 'tBodyGyro-entropy()-X', 'tBodyGyroJerkMag-min()', 'tBodyAccJerkMag-arCoeff()2',
              'tBodyGyro-entropy()-Y', 'fBodyAccJerk-mad()-X', 'tBodyGyroJerk-correlation()-Y,Z',
              'tBodyGyro-correlation()-X,Y', 'angle(Y,gravityMean)', 'tGravityAcc-max()-Y',
              'tBodyAccJerk-correlation()-Y,Z', 'tBodyGyroJerk-correlation()-X,Z', 'fBodyGyro-bandsEnergy()-9,16',
              'tBodyGyroMag-arCoeff()2', 'fBodyBodyGyroJerkMag-min()', 'tBodyGyroJerk-max()-X',
              'tBodyAccJerk-entropy()-X', 'tBodyAccJerkMag-max()', 'fBodyAcc-bandsEnergy()-49,56',
              'fBodyAccJerk-mad()-Z', 'fBodyGyro-max()-Z', 'tBodyAcc-max()-Z', 'tBodyGyro-arCoeff()-Y,3',
              'tGravityAcc-correlation()-X,Y', 'fBodyGyro-iqr()-Y', 'tBodyAcc-arCoeff()-Y,2',
              'tBodyGyroMag-entropy()', 'fBodyAccJerk-bandsEnergy()-1,24', 'fBodyAcc-meanFreq()-Y',
              'fBodyBodyGyroMag-mad()', 'tBodyGyroJerk-arCoeff()-Y,2', 'fBodyAcc-entropy()-X', 'fBodyGyro-std()-Z',
              'fBodyAccJerk-std()-Z', 'fBodyAccJerk-entropy()-Y', 'fBodyBodyAccJerkMag-entropy()',
              'fBodyAccJerk-max()-X', 'tBodyAccJerk-min()-X', 'fBodyBodyGyroMag-min()', 'tGravityAccMag-entropy()',
              'fBodyGyro-skewness()-X', 'fBodyAccJerk-iqr()-X', 'fBodyBodyGyroJerkMag-skewness()',
              'tBodyAccMag-mean()', 'fBodyGyro-entropy()-Z', 'fBodyAcc-mad()-X', 'tBodyGyro-mean()-X',
              'fBodyAcc-energy()-Z', 'tBodyAccJerk-iqr()-Y', 'fBodyGyro-max()-X', 'tBodyAcc-mean()-Z',
              'fBodyAccJerk-bandsEnergy()-49,64', 'fBodyAcc-kurtosis()-Z', 'tBodyGyroJerk-entropy()-X',
              'fBodyAccJerk-mean()-Y', 'tBodyGyro-arCoeff()-Y,2', 'tGravityAcc-entropy()-Y', 'tBodyAccJerk-energy()-Y',
              'fBodyGyro-meanFreq()-X', 'tBodyAcc-arCoeff()-Y,1', 'fBodyBodyAccJerkMag-mad()',
              'tBodyAccJerkMag-mean()', 'fBodyAccJerk-bandsEnergy()-1,16', 'tGravityAcc-energy()-Y',
              'tBodyGyroMag-arCoeff()4', 'fBodyAcc-std()-X', 'tGravityAcc-mean()-X', 'fBodyAccJerk-min()-Z',
              'fBodyAcc-mean()-Z', 'tBodyGyroJerk-correlation()-X,Y', 'fBodyGyro-mean()-Z', 'fBodyGyro-mad()-X',
              'tGravityAcc-iqr()-Y', 'tBodyAcc-sma()', 'fBodyAccJerk-maxInds-X', 'fBodyGyro-kurtosis()-X',
              'fBodyBodyGyroJerkMag-maxInds', 'fBodyAcc-iqr()-Y', 'tBodyAccJerk-iqr()-X',
              'fBodyAcc-bandsEnergy()-1,16', 'fBodyAcc-bandsEnergy()-1,8', 'tBodyAccJerk-sma()',
              'tBodyGyroJerk-iqr()-Y', 'fBodyGyro-energy()-Z', 'tBodyGyro-iqr()-Y', 'fBodyAcc-energy()-Y',
              'fBodyAccJerk-bandsEnergy()-57,64', 'fBodyAccJerk-bandsEnergy()-33,48', 'tBodyAccJerk-mean()-Y',
              'tGravityAccMag-arCoeff()4', 'fBodyGyro-mean()-X', 'fBodyGyro-entropy()-Y', 'tBodyGyro-sma()',
              'fBodyGyro-kurtosis()-Y', 'tGravityAccMag-arCoeff()2', 'fBodyAccMag-iqr()', 'tGravityAccMag-sma()',
              'tGravityAccMag-max()', 'fBodyBodyAccJerkMag-maxInds', 'tBodyAccMag-arCoeff()1',
              'tBodyGyroJerkMag-arCoeff()3', 'angle(tBodyGyroJerkMean,gravityMean)', 'tBodyAccMag-iqr()',
              'fBodyBodyGyroJerkMag-energy()', 'fBodyAccJerk-std()-Y', 'fBodyAccJerk-bandsEnergy()-25,48',
              'tBodyAccMag-arCoeff()2', 'fBodyAcc-mad()-Y', 'fBodyAcc-bandsEnergy()-1,24', 'tBodyAccJerkMag-mad()',
              'tBodyAccJerk-arCoeff()-Y,1', 'tBodyGyro-max()-Y', 'fBodyAcc-maxInds-Y', 'fBodyGyro-skewness()-Y',
              'tBodyAcc-std()-X', 'tBodyGyroJerk-min()-X', 'fBodyAccJerk-meanFreq()-X', 'fBodyAcc-kurtosis()-X',
              'fBodyBodyGyroJerkMag-entropy()', 'tBodyGyroJerkMag-max()', 'fBodyAccMag-std()',
              'fBodyAccJerk-skewness()-Y', 'fBodyAccJerk-bandsEnergy()-17,24', 'tBodyAccJerkMag-arCoeff()1',
              'fBodyAccMag-skewness()', 'fBodyBodyAccJerkMag-mean()', 'tBodyGyroMag-sma()', 'tGravityAcc-std()-Y',
              'fBodyBodyAccJerkMag-skewness()', 'tBodyGyro-iqr()-Z', 'tGravityAcc-arCoeff()-X,1',
              'fBodyAcc-max()-Y', 'fBodyBodyGyroMag-max()', 'fBodyGyro-iqr()-X', 'tBodyAcc-mad()-X',
              'fBodyAcc-iqr()-Z', 'fBodyBodyGyroMag-std()', 'tBodyAcc-arCoeff()-Y,4', 'fBodyAcc-skewness()-Z',
              'tBodyAccMag-min()', 'fBodyBodyGyroMag-meanFreq()', 'fBodyAccJerk-bandsEnergy()-49,56',
              'tBodyGyro-std()-Z', 'tBodyGyro-arCoeff()-Z,4', 'tGravityAcc-arCoeff()-Z,2', 'tBodyGyroJerk-max()-Y',
              'fBodyGyro-std()-Y', 'fBodyAccJerk-bandsEnergy()-25,32', 'tBodyAccJerk-std()-X',
              'fBodyAccJerk-bandsEnergy()-9,16', 'tBodyGyroJerk-std()-X', 'tBodyAcc-mean()-Y',
              'tBodyGyroJerk-std()-Y', 'fBodyGyro-maxInds-Z', 'tBodyGyroMag-max()', 'tGravityAcc-std()-Z',
              'fBodyAcc-meanFreq()-Z', 'tBodyGyroMag-arCoeff()3', 'fBodyBodyGyroJerkMag-sma()', 'tGravityAcc-std()-X',
              'tGravityAcc-mad()-X', 'fBodyGyro-bandsEnergy()-41,48', 'tGravityAcc-entropy()-X', 'tBodyAcc-mad()-Z',
              'tBodyAccJerk-energy()-X', 'fBodyAccJerk-energy()-Z', 'tBodyGyroJerk-arCoeff()-X,3',
              'tBodyAccJerkMag-energy()', 'fBodyAccJerk-iqr()-Z', 'tBodyGyroJerkMag-mean()', 'tBodyAccJerkMag-sma()',
              'angle(tBodyGyroMean,gravityMean)', 'tBodyAcc-energy()-Z', 'tBodyAccJerk-min()-Y', 'tBodyAcc-iqr()-Z',
              'tBodyGyro-energy()-Y', 'tBodyAccJerk-arCoeff()-X,4', 'tBodyAcc-arCoeff()-Z,1',
              'tGravityAcc-arCoeff()-Z,1', 'tGravityAcc-min()-Z', 'fBodyAccMag-max()', 'tBodyGyroJerk-arCoeff()-Y,4',
              'tBodyGyro-mad()-X', 'fBodyBodyGyroJerkMag-meanFreq()', 'fBodyAcc-sma()', 'tGravityAcc-mad()-Z',
              'fBodyBodyGyroMag-maxInds', 'tBodyAcc-arCoeff()-Z,4', 'tBodyGyroJerk-min()-Y',
              'fBodyAcc-bandsEnergy()-17,24', 'tBodyGyro-arCoeff()-Z,2', 'fBodyGyro-meanFreq()-Y',
              'fBodyBodyGyroJerkMag-max()', 'fBodyAccJerk-std()-X', 'fBodyGyro-energy()-X', 'fBodyAcc-meanFreq()-X',
              'tGravityAccMag-min()', 'tBodyAccJerkMag-entropy()', 'tBodyGyro-energy()-X', 'tBodyAccJerk-mean()-X',
              'tGravityAcc-mad()-Y', 'tBodyGyro-arCoeff()-X,1', 'tBodyAccJerk-arCoeff()-Z,4', 'tBodyGyro-entropy()-Z',
              'fBodyGyro-bandsEnergy()-33,48', 'tGravityAcc-mean()-Z', 'tBodyGyro-arCoeff()-Y,4',
              'tBodyAccJerk-entropy()-Y', 'tBodyGyroMag-min()', 'fBodyGyro-sma()', 'fBodyAccMag-kurtosis()',
              'tBodyAccJerk-entropy()-Z', 'tBodyGyro-min()-Y', 'fBodyBodyAccJerkMag-min()',
              'fBodyAcc-bandsEnergy()-41,48', 'tGravityAcc-min()-X', 'fBodyGyro-max()-Y', 'tBodyAccMag-arCoeff()4',
              'fBodyAcc-bandsEnergy()-49,64', 'tGravityAcc-arCoeff()-Y,3', 'tBodyGyro-max()-Z',
              'fBodyAccJerk-bandsEnergy()-33,40', 'tBodyAccJerk-max()-Z', 'tBodyGyroJerk-mad()-Z',
              'tBodyAccJerkMag-arCoeff()3', 'angle(tBodyAccMean,gravity)', 'tBodyGyroJerk-iqr()-X',
              'fBodyBodyGyroMag-mean()', 'fBodyAcc-bandsEnergy()-25,48', 'fBodyGyro-energy()-Y',
              'fBodyAccMag-energy()', 'tGravityAcc-arCoeff()-Y,4', 'tBodyGyroJerk-energy()-Y',
              'fBodyAcc-bandsEnergy()-9,16', 'tBodyAccJerk-min()-Z', 'fBodyBodyGyroJerkMag-mad()',
              'fBodyGyro-bandsEnergy()-1,8', 'tGravityAcc-arCoeff()-X,3', 'fBodyAcc-maxInds-X',
              'tBodyAcc-min()-Y', 'fBodyGyro-entropy()-X', 'tBodyGyroJerkMag-mad()', 'fBodyBodyGyroMag-energy()',
              'fBodyAccJerk-maxInds-Z', 'tGravityAccMag-mad()', 'fBodyAccMag-min()', 'tBodyGyro-std()-Y',
              'fBodyGyro-bandsEnergy()-25,32', 'tBodyAccJerk-iqr()-Z', 'tGravityAccMag-energy()',
              'tBodyGyroJerk-arCoeff()-Z,1', 'tBodyAccMag-std()', 'fBodyGyro-bandsEnergy()-49,56',
              'fBodyAcc-bandsEnergy()-33,40', 'fBodyAcc-min()-X', 'tBodyGyroJerk-arCoeff()-X,1',
              'tBodyGyro-mean()-Y', 'fBodyBodyGyroMag-sma()', 'tBodyGyro-arCoeff()-X,4', 'tGravityAccMag-arCoeff()3',
              'tBodyGyroJerk-std()-Z', 'tBodyAcc-energy()-X', 'fBodyAcc-bandsEnergy()-33,48', 'tBodyAcc-arCoeff()-Z,2',
              'tBodyAccJerk-energy()-Z', 'tGravityAcc-energy()-Z', 'fBodyBodyGyroMag-kurtosis()',
              'tBodyAccJerk-arCoeff()-X,3', 'fBodyGyro-mad()-Z', 'tBodyAcc-max()-X', 'fBodyGyro-meanFreq()-Z',
              'fBodyBodyAccJerkMag-sma()', 'tBodyAccJerk-arCoeff()-X,1', 'tBodyGyroJerk-arCoeff()-Z,3',
              'fBodyAcc-skewness()-Y', 'fBodyGyro-mean()-Y', 'fBodyBodyGyroMag-skewness()', 'fBodyBodyGyroMag-iqr()',
              'tGravityAcc-energy()-X', 'fBodyBodyGyroJerkMag-std()', 'tBodyAccJerk-arCoeff()-Z,2',
              'tBodyAccMag-max()', 'tBodyAccMag-mad()', 'tBodyGyroJerkMag-arCoeff()2', 'fBodyGyro-bandsEnergy()-1,16',
              'tBodyAccJerk-arCoeff()-Y,3', 'tBodyGyroJerk-arCoeff()-X,2', 'tBodyAccJerk-arCoeff()-Y,4',
              'tBodyGyroMag-std()', 'fBodyAccJerk-bandsEnergy()-41,48', 'tBodyAcc-arCoeff()-X,2',
              'tGravityAcc-arCoeff()-Y,2', 'fBodyAcc-mad()-Z', 'tBodyGyro-arCoeff()-Z,1', 'fBodyGyro-min()-X',
              'tBodyGyroJerk-energy()-Z', 'tGravityAcc-entropy()-Z', 'fBodyAccJerk-entropy()-X',
              'fBodyAcc-maxInds-Z', 'tBodyAcc-entropy()-Y', 'tBodyGyro-mad()-Y', 'tBodyGyroJerk-energy()-X',
              'fBodyAcc-iqr()-X', 'angle(Z,gravityMean)', 'tBodyAccJerkMag-arCoeff()4', 'fBodyAccMag-meanFreq()',
              'tBodyAccJerk-mean()-Z', 'tBodyGyroJerkMag-entropy()', 'tBodyAccJerk-arCoeff()-Z,3', 'fBodyAcc-std()-Y',
              'fBodyAccMag-entropy()', 'tBodyGyroJerkMag-iqr()', 'tGravityAcc-max()-X', 'tBodyGyroMag-mean()',
              'tBodyAccMag-sma()']

calc_fied = 'Activity'
train_file = 'datasets/train.csv'
test_file = 'datasets/test.csv'

func_description ={'init_datasets':'Загрузка датасета','gradient':'Вычисление градиентного бустинга',
                   'yandex':'Вычисление  CatBoosting','ada_boost':'Вычисление Ada Boost',
                   'extra_tree':'Вычисление Extra Trees','sqr_boost':'Вычисление QDA',
                   'LGBM_method':'Вычисление Light Gradient Boosting Machine',
                   'KNN_method':'K ближайших соседей','decision_tree_method':'Классификатор дерева решений',
                   'extremally_gradient_method':'Экстремальный градиентный бустинг',
                   'dumn_method':'Фиктивный классификатор','SVM_method':'SVM - линейное ядро'
}
